// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwkutvrzkhrxfdyyewap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3a3V0dnJ6a2hyeGZkeXlld2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMzczODUsImV4cCI6MjA1NTkxMzM4NX0.ydGKp4w9bKV3rWRPs4a8mTsAAJElqycJgjUhx1sa2RY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);